url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Live with Code" # the name of your site, e.g. ACME Corp.


include:
  - _pages
  - _posts
  - _layouts
  - js
  - images


defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext